### ISSUE TITLE
后续是否有支持登录账号的计划？用来支持vip歌曲播放

### ISSUE THREAD

**Issue by kecikeci** [honmaple/meting-api#2]
后续是否有支持登录账号的计划？用来支持vip歌曲播放

**Comment by honmaple** [comment]
不会添加登录账号的功能，如果需要支持vip歌曲，可以尝试设置cookies请求头，比如：`netease.headers.Cookie: "xxxxx"`，或者自行部署 **Binaryify/NeteaseCloudMusicApi**，并设置 `netease_api.host`
